name: 'Build Creation'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install and setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
        
      - name: Create project build
        run: |
          npm run build
          echo "✅ Build created successfully!"
          ls -la .next/

      - name: Creating a build directory
        run: mkdir -p build

      - name: Moving all the files to the build directory
        run: |
          mv .next/* build/ || echo "No files to move"
          echo "📦 Contents of build directory:"
          ls -la build/

      - name: Add the local build to the repository
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: build/
          if-no-files-found: error